version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8080"
    depends_on:
      - "psql"

  psql:
    image: postgres:13-alpine
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1000.sql
      - ./sql/testData.sql:/docker-entrypoint-initdb.d/9000.sql
    ports:
      - '5432:5432'
volumes:
  database-data: